### ISSUE TITLE
Emby API token request `Object reference not set to an instance of an object.`

### ISSUE THREAD

**Issue by wouterdebruijn** [faush01/playback_reporting#14]
Hi

In its current state, it is not possible to fetch data using a Emby API Token instead of an actual user. This is because of the current admin validation check structured as follows:
```
            UserPolicy policy = _userManager.GetUserPolicy(auth_user_info.User);
            if (!policy.IsAdministrator)
            {
                return new List<Dictionary<string, object>>();
            }
```
Where `GetUserPolicy` returns a Null object which isn't caught.

It would be preferable to check if a valid API token is used and proceed accordingly. 

## Reproduce error
Create a new Emby API token and try to execute a GET request to the plugin.
`http://emby.server.example/emby/user_usage_stats/session_list`
Returns:
`Error 500: Object reference not set to an instance of an object.`

## Error reported by Emby containing host system information:
```
2023-01-04 14:26:48.601 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.0.21
	Command line: /usr/lib/emby-server/EmbyServer.dll -programdata /var/lib/emby -ffdetect /usr/bin/ffdetect-emby -ffmpeg /usr/bin/ffmpeg-emby -ffprobe /usr/bin/ffprobe-emby -restartexitcode 3
	Operating system: Linux version 6.1.1-arch1-1 (linux@archlinux) (gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.39.0) #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000
	Framework: .NET 6.0.12
	OS/Process: x64/x64
	Runtime: usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.12/System.Private.CoreLib.dll
	Processor count: 4
	Data path: /var/lib/emby
	Application path: /usr/lib/emby-server
	System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
	   at Emby.Server.Implementations.Library.UserManager.GetUserPolicy(User user)
	   at playback_reporting.Api.UserActivityAPI.Get(GetSessionInfo request)
	   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: MediaBrowser.Model.Users.UserPolicy GetUserPolicy(MediaBrowser.Controller.Entities.User)
```

**Comment by faush01** [comment]
release now available with this fix.
